# Fichier values.yaml personnalisé pour kube-prometheus-stack

## Configuration principale de Prometheus
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchNames:
        - airflow
    ## Activer la découverte cross-namespace
    serviceMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}

    ## Ajouter le namespace airflow aux cibles
    namespaceSelector:
      any: true

    ## Configuration supplémentaire pour scraper les pods Airflow
    additionalScrapeConfigs:
      - job_name: "airflow-pods"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - airflow
        relabel_configs:
          - source_labels:
              [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels:
              [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__

## Configuration de l'opérateur Prometheus
prometheusOperator:
  ## Activer la surveillance du namespace airflow
  namespaces:
    releaseNamespace: true
    additional:
      - airflow

## Configuration RBAC
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources:
        - pods
        - services
        - endpoints
        - nodes
      verbs: ["get", "list", "watch"]

## Configuration Grafana
grafana:
  service:
    type: NodePort

## Configuration Alertmanager
alertmanager:
  service:
    type: NodePort
