apiVersion: v1
kind: Secret
metadata:
  name: sql-conn
  namespace: airflow
type: Opaque
data:
  DATABASE: cG9zdGdyZXM= # base64 encoded
  USER: cG9zdGdyZXM= # base64 encoded
  PASSWORD: cG9zdGdyZXM= # base64 encoded '
