apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: api
type: Opaque
data:
  PASSWORD: cG9zdGdyZXM= # base64 encoded '
stringData:
  SECRET_KEY: "azertyuiop^$*qsdfghjklmù<wxcvbn,;:!789456123"
  ALGORITHM: "HS256"
  TMDB_API_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZWY5MGUyOWMzZGQ0ZTg0Y2IzMjdhMWRiMzlhNWY1MSIsIm5iZiI6MTczMTAwMjkyOC44MzM2NTczLCJzdWIiOiI2NzI3Y2MwNTU5MTgxMzdjZmMzOTljMmQiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.rfjWSNDMqPka_PXWbTKEUt6pVHg4g_7nukU7yYU1Img"
