# ConfigMap pour les services MLflow et API
apiVersion: v1
kind: ConfigMap
metadata:
  name: posgres-mlfow-config
  namespace: reco-movies
data:
  POSTGRES_DB: "mlflow"
  POSTGRES_USER: "mlflow"
  MLFLOW_S3_ENDPOINT_URL: "http://s3-artifact-storage:9000"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-api-config
  namespace: reco-movies
data:
  POSTGRES_DB: "reco_movies"
  POSTGRES_USER: "antoine"

---
# ConfigMap pour Prometheus (Configuration)
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: reco-movies
data:
  prometheus.yml: |
    global:
      scrape_interval: '15s'
    scrape_configs:
      - job_name: 'fastapi'
        static_configs:
          - targets: ['fastapi-service:8000']

---
# Configmap pour fastapi
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: reco-movies
data:
  MODEL_PATH: "/app/model/model.pkl"
  DATA_PATH: "/app/raw/movies.csv"
  HOST: "0.0.0.0"
  PORT: "8000"
