apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: api
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.api.svc.cluster.local:9090
        isDefault: true
