# ConfigMap pour Prometheus (Configuration)
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: api
data:
  prometheus.yml: |
    global:
      scrape_interval: '15s'
    scrape_configs:
      - job_name: "node_exporter"
        static_configs:
          - targets: ["node_exporter.api.svc.cluster.local:9100"]
      - job_name: "fastapi"
        static_configs:
          - targets: ["fastapi.api.svc.cluster.local:8000"]
      - job_name: "airflow"
        static_configs:
          - targets: ["airflow-statsd.airflow.svc.cluster.local:9102"]
        metrics_path: "/metrics"
