# Airflow Scheduler Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: reco-movies
spec:
  replicas: 1 # Un seul scheduler est nécessaire dans une configuration standard.
  selector:
    matchLabels:
      app: airflow-scheduler # Label utilisé par le service.
  template:
    metadata:
      labels:
        app: airflow-scheduler # Labels du pod.
    spec:
      containers:
        - name: scheduler # Nom du conteneur.
          image: antoinepela/projet_reco_movies:airflow-scheduler-latest
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://antoine@api-postgres:5432/reco_movies
            - name: AIRFLOW__CORE__EXECUTOR
              value: CeleryExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__CORE__FERNET_KEY
              value: "YXJlbnRvaW5lcGVsYQ=="
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "False"
            - name: AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE
              value: "False"
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /usr/local/airflow/dags

---
# Airflow Worker Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: reco-movies
spec:
  replicas: 2 # Plusieurs workers peuvent être nécessaires.
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
        - name: airflow-worker
          image: antoinepela/projet_reco_movies:airflow-worker-latest

---
# Airflow Webserver Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: antoinepela/projet_reco_movies:airflow-webserver-latest

---
# Airflow Flower Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-flower
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-flower
  template:
    metadata:
      labels:
        app: airflow-flower
    spec:
      containers:
        - name: airflow-flower
          image: antoinepela/projet_reco_movies:airflow-flower-latest
