apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: antoinepela/projet_reco_movies:fastapi-latest
          imagePullPolicy: Always # Force Kubernetes à toujours tirer l'image
          env:
            - name: DATABASE
              value: "postgres"
            - name: USER
              value: "postgres"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: ALGORITHM
            - name: TMDB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: TMDB_API_TOKEN
            - name: UVICORN_RELOAD
              value: "false"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: models-storage-pvc
              mountPath: /models
      volumes:
        - name: models-storage-pvc
          persistentVolumeClaim:
            claimName: models-storage-pvc
