apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: airflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      annotations:
        prometheus.io/scrape: "true" # Indique que Prometheus doit scrapper ce Pod.
        prometheus.io/port: "8080" # Port sur lequel les métriques sont exposées.
        prometheus.io/path: "/metrics" # Chemin où les métriques sont disponibles.
    spec:
      containers:
        - name: fastapi
          image: antoinepela/projet_reco_movies:fastapi-latest
          imagePullPolicy: Always # Force Kubernetes à toujours tirer l'image
          env:
            - name: POSTGRES_HOST
              value: "airflow-postgresql.airflow.svc.cluster.local"
            - name: POSTGRES_DB # Nom de la base de données à créer.
              value: "postgres"
            - name: POSTGRES_USER # Nom d'utilisateur pour PostgreSQL.
              value: "postgres"
            - name: POSTGRES_PASSWORD # Mot de passe pour l'utilisateur.
              valueFrom:
                secretKeyRef:
                  name: sql-conn
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sql-conn
                  key: SECRET_KEY
            - name: ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: sql-conn
                  key: ALGORITHM
            - name: TMDB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sql-conn
                  key: TMDB_API_TOKEN
            - name: UVICORN_RELOAD
              value: "false"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: airflow-local-data-folder
              mountPath: /root/mount_file
      volumes:
        - name: airflow-local-data-folder
          persistentVolumeClaim:
            claimName: airflow-local-data-folder