apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: reco-movies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: antoinepela/projet_reco_movies:fastapi-latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: processed-movies-volume
              mountPath: /app/raw/processed_movies.csv
            - name: processed-ratings-volume
              mountPath: /app/raw/processed_ratings.csv
            - name: processed-links-volume
              mountPath: /app/raw/processed_links.csv
            - name: model-knn-volume
              mountPath: /app/models/model_KNN.pkl
            - name: model-svd-volume
              mountPath: /app/models/model_SVD.pkl
      volumes:
        - name: movies-volume
          persistentVolumeClaim:
            claimName: pvc-processed-movies
        - name: ratings-volume
          persistentVolumeClaim:
            claimName: pvc-processed-ratings
        - name: links-volume
          persistentVolumeClaim:
            claimName: pvc-processed-links
        - name: model-knn-volume
          persistentVolumeClaim:
            claimName: pvc-model-knn
        - name: model-svd-volume
          persistentVolumeClaim:
            claimName: pvc-model-svd
