apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: reco-movies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: antoinepela/projet_reco_movies:fastapi-latest
          imagePullPolicy: Always # Force Kubernetes à toujours tirer l'image
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-api-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-api-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-api-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "postgres-api-service"
            - name: UVICORN_RELOAD
              value: "false"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: model-knn-volume
              mountPath: /app/models/model_KNN.pkl
            - name: model-svd-volume
              mountPath: /app/models/model_SVD.pkl
      volumes:
        - name: model-knn-volume
          persistentVolumeClaim:
            claimName: pvc-model-knn
        - name: model-svd-volume
          persistentVolumeClaim:
            claimName: pvc-model-svd
