apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow-webserver
          image: antoinepela/projet_reco_movies:mlflow-webserver-latest
          ports:
            - containerPort: 5000
          args: ["mlflow", "server", "--host", "0.0.0.0"]
          envFrom:
            - configMapRef:
                name: postgres-mlflow-config
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio-service:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: postgres-mlflow-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-mlflow-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: POSTGRES_PASSWORD # Ajoutez cette ligne pour inclure le mot de passe PostgreSQL.
              valueFrom:
                secretKeyRef:
                  name: postgres-mlflow-secrets
                  key: POSTGRES_PASSWORD
