apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: antoinepela/projet_reco_movies:node-exporter-latest
          ports:
            - containerPort: 9100 # Port exposé pour Node Exporter.
