apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true" # Indique que Prometheus doit scrapper ce Pod.
        prometheus.io/port: "9100" # Port sur lequel les métriques sont exposées.
        prometheus.io/path: "/metrics" # Chemin où les métriques sont disponibles.
    spec:
      containers:
        - name: node-exporter
          image: antoinepela/projet_reco_movies:node-exporter-latest
          ports:
            - containerPort: 9100 # Port exposé pour Node Exporter.
