apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@pgadmin.org" # Email par défaut pour se connecter
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin" # Mot de passe par défaut pour se connecter
