apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
            - name: SCRIPT_NAME
              value: ""
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "False"
            - name: PGADMIN_CONFIG_LOGIN_BANNER
              value: "False"
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/pgadmin4/servers.json"
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-data
          securityContext:
            runAsUser: 5050
          ports:
            - containerPort: 80
      volumes:
        - name: pgadmin-data
          emptyDir: {}
