apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-postgres
  namespace: reco-movies
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-postgres
  template:
    metadata:
      labels:
        app: api-postgres
    spec:
      containers:
        - name: postgres-api
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-api-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-api-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-api-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: combined-volume
              mountPath: /docker-entrypoint-initdb.d # Montez ici pour accéder à init.sql et aux fichiers CSV
      volumes:
        - name: combined-volume
          projected:
            sources:
              - configMap:
                  name: init-sql
              - persistentVolumeClaim:
                  claimName: pvc-processed-raw
        - name: pg-data
          persistentVolumeClaim:
            claimName: postgres-api-volume
