apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-postgres
  namespace: reco-movies
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-postgres
  template:
    metadata:
      labels:
        app: api-postgres
    spec:
      containers:
        - name: postgres-api
          image: antoinepela/projet_reco_movies:postgres-api-latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-api-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-api-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-api-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "postgres-api-service"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
            - name: processed-movies-volume
              mountPath: /docker-entrypoint-initdb.d/processed_movies.csv
            - name: processed-ratings-volume
              mountPath: /docker-entrypoint-initdb.d/processed_ratings.csv
            - name: processed-links-volume
              mountPath: /docker-entrypoint-initdb.d/processed_links.csv
            - name: users-volume
              mountPath: /docker-entrypoint-initdb.d/users.csv
      volumes:
        - name: init-sql
          hostPath:
            path: /home/antoine/jul24_cmlops_reco_film/postgres/init.sql
        - name: processed-movies-volume
          hostPath:
            path: /home/antoine/jul24_cmlops_reco_film/ml/data/processed/processed_movies.csv
        - name: processed-ratings-volume
          hostPath:
            path: /home/antoine/jul24_cmlops_reco_film/ml/data/processed/processed_ratings.csv
        - name: processed-links-volume
          hostPath:
            path: /home/antoine/jul24_cmlops_reco_film/ml/data/processed/processed_links.csv
        - name: users-volume
          hostPath:
            path: /home/antoine/jul24_cmlops_reco_film/ml/data/processed/users.csv
        - name: pg-data
          persistentVolumeClaim:
            claimName: pvc-postgres-api-volume
