# Déploiement Postgres pour MLflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgres
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mlflow
  template:
    metadata:
      labels:
        app: postgres-mlflow
    spec:
      containers:
        - name: postgres-mlflow
          image: antoinepela/projet_reco_movies:postgres-mlflow-latest
          envFrom:
            - configMapRef:
                name: postgres-mlflow-config
            - secretRef:
                name: postgres-mlflow-secrets
          ports:
            - containerPort: 5429 # Port personnalisé pour MLflow DB
