apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: reco-movies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter # Utilisez l'image officielle de Postgres Exporter.
          ports:
            - containerPort: 9187 # Port exposé pour Postgres Exporter.
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)?sslmode=disable" # Informations de connexion à la base de données.
          envFrom:
            - configMapRef:
                name: postgres-api-config
            - secretRef:
                name: postgres-api-secrets # Référence au secret contenant les informations d'authentification.

