apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
