apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-raw-preprocess-folder
  namespace: airflow
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
