# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-logs-folder
  namespace: airflow # Namespace où le PVC sera créé
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce # Mode d'accès requis pour le PVC
  resources:
    requests:
      storage: 10Gi # Capacité demandée par le PVC
