apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-dags-folder
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  claimRef:
    namespace: airflow
    name: airflow-local-dags-folder
  hostPath:
    path: "/host/kubernetes/airflow/dags"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-local-dags-folder
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
