apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-logs-folder-pv
spec:
  capacity:
    storage: 2Gi # Capacité du PV
  accessModes:
    - ReadWriteOnce # Mode d'accès
  storageClassName: local-path
  claimRef:
    namespace: airflow # Namespace pour le PVC qui utilise ce PV
    name: airflow-local-logs-folder-pvc
  hostPath:
    path: "/host/kubernetes/airflow/logs"
