apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-local-logs-folder
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi # Capacité du PV
  accessModes:
    - ReadWriteOnce # Mode d'accès
  claimRef:
    namespace: airflow # Namespace pour le PVC qui utilise ce PV
    name: airflow-local-logs-folder
  hostPath:
    path: "/host/kubernetes/airflow/logs"
