# pvc-minio-data.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minio-data
  namespace: reco-movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Doit correspondre à la taille du PV.
