apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-mlflow-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: airflow
    name: models-mlflow-pvc
  hostPath:
    path: "/host/data/models"
