apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  claimRef:
    namespace: airflow
    name: models-pvc
  hostPath:
    path: "/host/kubernetes/mlflow/models"
