apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
  namespace: reco-movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
