apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-api-postgres-pvc
  namespace: airflow
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
