apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-db-backup
  namespace: airflow
spec:
  storageClassName: local-path
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: airflow
    name: my-db-backup
  hostPath:
    path: "/host/data/backup_db"
