### CREATION DES PVC

# pvc-posgres-api-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-api-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/antoine/jul24_cmlops_reco_film/postgres/postgres_data"
  volumeMode: Filesystem
---
# pvc-posgres-api-volume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-api-volume
  namespace: reco-movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
