apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-processed-data
  namespace: reco-movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
