apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: api
    name: prometheus-pvc
  hostPath:
    path: "/host/kubernetes/prometheus/logs"
