apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080 # Port sur lequel le webserver Airflow écoute
      targetPort: 8080
  type: ClusterIP
