apiVersion: v1
kind: Service
metadata:
  name: airflow-statsd
  namespace: airflow
  labels:
    app: airflow-statsd # Doit matcher le selector du ServiceMonitor
spec:
  ports:
    - name: metrics # <-- Nom requis pour le ServiceMonitor
      port: 9102
      protocol: TCP
  selector:
    app: airflow-statsd
