apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: api
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: api
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501 # Port par défaut pour Streamlit

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-monitor
  namespace: prom
spec:
  selector:
    matchLabels:
      app: fastapi
  namespaceSelector:
    matchNames:
      - api  # Le namespace où se trouve notre service FastAPI
  endpoints:
    - port: "80"
      interval: 30s  # Intervalle de scraping
      scrapeTimeout: 10s  # Timeout pour le scraping