
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: airflow
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501 # Port par défaut pour Streamlit
      targetPort: 8501
      nodePort: 30007 # Port NodePort spécifique (facultatif)
  type: ClusterIP

