apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: api
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: api
spec:
  selector:
    app: streamlit # Assurez-vous que ce label correspond à celui de votre pod Streamlit
  ports:
    - protocol: TCP
      port: 8501 # Port par défaut pour Streamlit

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: api
spec:
  selector:
    app: node-exporter # Assurez-vous que ce label correspond à celui de votre pod Streamlit
  ports:
    - protocol: TCP
      port: 9100 # Port par défaut pour Streamlit

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: api
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: api
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000 # Port externe sur lequel le service sera accessible.
      targetPort: 3000 # Port du conteneur Grafana.
  type: NodePort # Changez en LoadBalancer si vous souhaitez un accès externe direct.
