apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: airflow
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: airflow
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501 # Port par défaut pour Streamlit
      targetPort: 8501 # Assurez-vous que c'est le bon port cible
      nodePort: 30007 # Port NodePort spécifique (facultatif)
  type: NodePort

