apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: airflow
spec:
  type: ClusterIP # Changez en NodePort si vous voulez accéder depuis l'extérieur du cluster
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: mlflow
