apiVersion: v1
kind: Service
metadata:
  name: my-api-postgres
  namespace: airflow
spec:
  type: ClusterIP
  ports:
    - port: 5432 # Port sur lequel le service sera accessible.
      targetPort: 5432 # Port du conteneur PostgreSQL.
      protocol: TCP
  selector:
    app: my-api-postgres
