# Services pour chaque application

## Service MLflow (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: reco-movies
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
## Service FastAPI (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: reco-movies
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort
---
## Service Streamlit (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: reco-movies
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30002
  type: NodePort
---
## Service Prometheus (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: reco-movies
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30003
  type: NodePort
---
## Service Grafana (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: reco-movies
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
  type: NodePort

---
## Service Postgres-API (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: postgres-api-service
  namespace: reco-movies
spec:
  selector:
    app: api-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---
## Service MinIO (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: reco-movies
spec:
  selector:
    app: s3-artifact-storage
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
      nodePort: 30005
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30006
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: reco-movies
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort

---
## Service Airflow Webserver (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-service
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort
