# Services pour chaque application

## Service MLflow (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: reco-movies
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
  type: ClusterIP

---
## Service FastAPI (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: reco-movies
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
  type: LoadBalancer
---
## Service Streamlit (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: reco-movies
spec:
  selector:
    app: streamlit
  ports:
    - port: 8501
  type: LoadBalancer
---
## Service Prometheus (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: reco-movies
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
  type: ClusterIP
---
## Service Grafana (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: reco-movies
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
  type: LoadBalancer

---

