services:
  db:
    container_name: reco_movies_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../ml/data/processed/processed_movies.csv:/docker-entrypoint-initdb.d/processed_movies.csv
      - ../ml/data/processed/processed_ratings.csv:/docker-entrypoint-initdb.d/processed_ratings.csv
      - ../ml/data/processed/processed_links.csv:/docker-entrypoint-initdb.d/processed_links.csv
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_reco_movies
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:5050"
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - backend

volumes:
  pg_data:
  pgadmin_data:

networks:
  backend:
    name: backend
    external: true