version: '3.8'
services:
  db:
    container_name: reco_movies_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5430:5432"
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /ml/data/processed/:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data # Volume pour persistance des données

  pgadmin:
    container_name: pgadmin4_reco_movies
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5431:80"
    networks:
      - backend

volumes:
  - pg_data:


networks:
  backend:
    name: backend
    external: true
