apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-data-folder
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/antoine/jul24_cmlops_reco_film/kubernetes/airflow/order/data/to_ingest"
