apiVersion: batch/v1
kind: Job
metadata:
  name: python-transform
spec:
  template:
    spec:
      containers:
        - name: python-transform
          image: antoinepela/projet_reco_movies:order-python-transform-latest
          command: ["python", "build_features.py"]
          volumeMounts:
            - name: order-data-folder
              mountPath: /app/data/to_ingest
      restartPolicy: Never
      volumes:
        - name: order-data-folder
          persistentVolumeClaim:
            claimName: order-data-folder
