name: Build and Push Docker Images

on:
  push:
    branches:
      - Antoine

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Airflow image
        uses: docker/build-push-action@v2
        with:
          context: ./airflow
          file: ./airflow/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/airflow:latest

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api:latest

      - name: Build and push MLflow image
        uses: docker/build-push-action@v2
        with:
          context: ./mlflow
          file: ./mlflow/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlflow:latest

      - name: Build and push Streamlit image
        uses: docker/build-push-action@v2
        with:
          context: ./streamlit
          file: ./streamlit/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/streamlit:latest