name: Python application

on:
  push:
    branches: ["Antoine"]
  pull_request:
    branches: ["Antoine"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r tests/requirements-test.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 tests/test_*.py --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=tests/Dags_airflow/*
          # exit-zero treats all errors as warnings
          flake8 tests/test_*.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=tests/Dags_airflow/*
      - name: Test with pytest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          pytest tests/test_api_auth.py
          pytest tests/test_api_predict.py
          pytest tests/test_build_features.py
          pytest tests/test_streamlit_app.py
          pytest tests/test_train_model.py
